### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by iMonZ** [BenjaminFaal/ps4-remote-pkg-installer#17]
Getting this message after installing multiple pkgs from drive:

Error installing:
org.springframework.web.client.ResourceAccessException: I/O error on Post request for "192.1.1.90:12800/api/install": Read times out; nested exception is java.net.SocketTimeoutException: Read timed out

**Comment by Gkiokan** [comment]
If you got timeouts this means RPI crashed or something happend that the installer can not access RPI on your ps4 anymore.  
Just restart RPI and it should work.  This happens if you get to hard on RPI on your ps4.

**Comment by iMonZ** [comment]
> If you got timeouts this means RPI crashed or something happend that the installer can not access RPI on your ps4 anymore. Just restart RPI and it should work. This happens if you get to hard on RPI on your ps4.

Thanks it worked.

Now I have a different error:

when I try to install multiple pkgs I get this error:


```

2022-01-10 21:19:29.750 ERROR 10610 --- [WT-EventQueue-0] c.b.ps4remotepkginstaller.ui.MainUI      : Error installing: 

java.util.concurrent.ExecutionException: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://192.168.1.28:12800/api/install": Server returned HTTP response code: 500 for URL: http://192.168.1.28:12800/api/install; nested exception is java.io.IOException: Server returned HTTP response code: 500 for URL: http://192.168.1.28:12800/api/install
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613) ~[na:na]
	at com.benjaminfaal.ps4remotepkginstaller.ui.MainUI$10.done(MainUI.java:894) ~[classes!/:0.0.7]
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) ~[na:na]
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) ~[na:na]
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) ~[na:na]
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) ~[na:na]
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317) ~[na:na]
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249) ~[na:na]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[na:na]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://192.168.1.28:12800/api/install": Server returned HTTP response code: 500 for URL: http://192.168.1.28:12800/api/install; nested exception is java.io.IOException: Server returned HTTP response code: 500 for URL: http://192.168.1.28:12800/api/install
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:784) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:436) ~[spring-web-5.3.3.jar!/:5.3.3]
	at com.benjaminfaal.ps4remotepkginstaller.service.impl.RemotePKGInstallerServiceImpl.install(RemotePKGInstallerServiceImpl.java:262) ~[classes!/:0.0.7]
	at com.benjaminfaal.ps4remotepkginstaller.service.impl.RemotePKGInstallerServiceImpl.installFiles(RemotePKGInstallerServiceImpl.java:174) ~[classes!/:0.0.7]
	at com.benjaminfaal.ps4remotepkginstaller.ui.MainUI.lambda$null$18(MainUI.java:792) ~[classes!/:0.0.7]
	at com.benjaminfaal.ps4remotepkginstaller.ui.MainUI$10.doInBackground(MainUI.java:888) ~[classes!/:0.0.7]
	at com.benjaminfaal.ps4remotepkginstaller.ui.MainUI$10.doInBackground(MainUI.java:885) ~[classes!/:0.0.7]
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://192.168.1.28:12800/api/install
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[na:na]
	at org.springframework.http.client.SimpleClientHttpResponse.getBody(SimpleClientHttpResponse.java:89) ~[spring-web-5.3.3.jar!/:5.3.3]
	at com.benjaminfaal.ps4remotepkginstaller.service.impl.RemotePKGInstallerServiceImpl.lambda$new$0(RemotePKGInstallerServiceImpl.java:90) ~[classes!/:0.0.7]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:775) ~[spring-web-5.3.3.jar!/:5.3.3]
	... 13 common frames omitted


```

**Comment by Gkiokan** [comment]
Puh. I am not into java but this seems to be a mass send error on the data array.  
There is no hint about the data array that is beeing sent to the RPI. Try to install them file by file.  

I am not sure if @BenjaminFaal can fix this quickly (last commit 12 months ago?)   
but If you are in hurry you may try my [PS4 PKG installer v2.4.3](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.4.3).

**Comment by iMonZ** [comment]
> Puh. I am not into java but this seems to be a mass send error on the data array. There is no hint about the data array that is beeing sent to the RPI. Try to install them file by file.
> 
> I am not sure if @BenjaminFaal can fix this quickly (last commit 12 months ago?) but If you are in hurry you may try my [PS4 PKG installer v2.4.3](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.4.3).

Thanks
I think sending multiple files was not intented.
A quick for i = quantity of files should be enough.

Thanks I would like to try this tool out, but my Mac is currently restoring and there is no Flatpak version of your tool available :(

**Comment by iMonZ** [comment]
> > Puh. I am not into java but this seems to be a mass send error on the data array. There is no hint about the data array that is beeing sent to the RPI. Try to install them file by file.
> > I am not sure if @BenjaminFaal can fix this quickly (last commit 12 months ago?) but If you are in hurry you may try my [PS4 PKG installer v2.4.3](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.4.3).
> 
> Thanks I think sending multiple files was not intented. A quick for i = quantity of files should be enough.
> 
> Thanks I would like to try this tool out, but my Mac is currently restoring and there is no Flatpak version of your tool available :(

So my Mac is actually restored.
But have you notarized your Mac build?
I think this is why I can't open that.
Do you have an Apple Developer account?

**Comment by Gkiokan** [comment]
Unfortunatelly it is not signed yet. I've a apple dev account but I will enroll the certifacte next month at earliest. :/ 
  
But you should be able to proceed without any error once you allow it access though system preferences.

**Comment by iMonZ** [comment]
> Unfortunatelly it is not signed yet. I've a apple dev account but I will enroll the certifacte next month at earliest. :/
> 
> But you should be able to proceed without any error once you allow it access though system preferences.

Im not able to do that anymore.
The system policies have blocked this and I can’t do anything about it.

**Comment by Gkiokan** [comment]
This is a good point. I'll add a guide to my Troubleshooting.  

Once you tried to open it mac blocks it, that is correct. You can check your System Preferences > Security > General 
There should be the app listed as blocked. You can explicity allow it then to run.  

In your case it should be listed here below App-Downloads .... 
![image](https://user-images.githubusercontent.com/7249224/148835962-d9a36061-38a6-41c2-9750-0c9af5aa9afd.png)

**Comment by iMonZ** [comment]
> This is a good point. I'll add a guide to my Troubleshooting.
> 
> Once you tried to open it mac blocks it, that is correct. You can check your System Preferences > Security > General There should be the app listed as blocked. You can explicity allow it then to run.
> 
> In your case it should be listed here below App-Downloads .... ![image](https://user-images.githubusercontent.com/7249224/148835962-d9a36061-38a6-41c2-9750-0c9af5aa9afd.png)

https://user-images.githubusercontent.com/11319871/148836410-60d8d3a2-3ead-4b50-b72a-2178539a2af6.mov

As I said its blocked by policies.


Please sign the app if you have an Developer profile.
It would be much better than telling people to disable their "Anti virus software"
This shouldn't get to a habit :(

A lot of people are telling to do that and its starts to get an habit

**Comment by iMonZ** [comment]
@Gkiokan 
Maybe I could create a formula for this application. 
This would resolve the issue.
Lets see if I have time in the next days

**Comment by Gkiokan** [comment]
Thanks for the video. Seeing that mac acts like this for the first time.  
Sure you are right regarding the dev profile.  

I didn't thought about brew yet, but that could fix some sort of trouble.  

If you mind, you could also clone the repo and run it with npm i && npm run watch to get the dev mode running or even compile it yourself with npm i && npm run build:mac. 

Sorry for the circumstances.

**Comment by iMonZ** [comment]
> Thanks for the video. Seeing that mac acts like this for the first time. Sure you are right regarding the dev profile.
> 
> I didn't thought about brew yet, but that could fix some sort of trouble.
> 
> If you mind, you could also clone the repo and run it with npm i && npm run watch to get the dev mode running or even compile it yourself with npm i && npm run build:mac.
> 
> Sorry for the circumstances.

That’s a great idea! Gonna do that!
Thanks for your support and your work :)
